// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/blueprint/archetypes/entity_behavior.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: General visualization behavior of an entity.
///
/// TODO(#6541): Fields of this archetype currently only have an effect when logged in the blueprint store.
#[derive(Clone, Debug, Default)]
pub struct EntityBehavior {
    /// Whether the entity can be interacted with.
    ///
    /// This property is propagated down the entity hierarchy until another child entity
    /// sets `interactive` to a different value at which point propagation continues with that value instead.
    ///
    /// Defaults to parent's `interactive` value or true if there is no parent.
    pub interactive: Option<SerializedComponentBatch>,

    /// Whether the entity is visible.
    ///
    /// This property is propagated down the entity hierarchy until another child entity
    /// sets `visible` to a different value at which point propagation continues with that value instead.
    ///
    /// Defaults to parent's `visible` value or true if there is no parent.
    pub visible: Option<SerializedComponentBatch>,

    /// Whether toggling this entity's visibility should propagate across views.
    ///
    /// When `true`, toggling this entity's `visible` override in one view also writes the same
    /// override to every other view whose contents contain this entity. Useful for keeping
    /// multi-step debug entities synchronized when you toggle them on or off.
    ///
    /// Defaults to `false` — each view manages its own visibility independently.
    pub link_visibility: Option<SerializedComponentBatch>,
}

impl EntityBehavior {
    /// Returns the [`ComponentDescriptor`] for [`Self::interactive`].
    ///
    /// The corresponding component is [`crate::components::Interactive`].
    #[inline]
    pub fn descriptor_interactive() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.blueprint.archetypes.EntityBehavior".into()),
            component: "EntityBehavior:interactive".into(),
            component_type: Some("rerun.components.Interactive".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::visible`].
    ///
    /// The corresponding component is [`crate::components::Visible`].
    #[inline]
    pub fn descriptor_visible() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.blueprint.archetypes.EntityBehavior".into()),
            component: "EntityBehavior:visible".into(),
            component_type: Some("rerun.components.Visible".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::link_visibility`].
    ///
    /// The corresponding component is [`crate::blueprint::components::LinkVisibility`].
    #[inline]
    pub fn descriptor_link_visibility() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.blueprint.archetypes.EntityBehavior".into()),
            component: "EntityBehavior:link_visibility".into(),
            component_type: Some("rerun.blueprint.components.LinkVisibility".into()),
        }
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 0usize]> =
    std::sync::LazyLock::new(|| []);

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 0usize]> =
    std::sync::LazyLock::new(|| []);

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 3usize]> =
    std::sync::LazyLock::new(|| {
        [
            EntityBehavior::descriptor_interactive(),
            EntityBehavior::descriptor_visible(),
            EntityBehavior::descriptor_link_visibility(),
        ]
    });

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 3usize]> =
    std::sync::LazyLock::new(|| {
        [
            EntityBehavior::descriptor_interactive(),
            EntityBehavior::descriptor_visible(),
            EntityBehavior::descriptor_link_visibility(),
        ]
    });

impl EntityBehavior {
    /// The total number of components in the archetype: 0 required, 0 recommended, 3 optional
    pub const NUM_COMPONENTS: usize = 3usize;
}

impl ::re_types_core::Archetype for EntityBehavior {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        "rerun.blueprint.archetypes.EntityBehavior".into()
    }

    #[inline]
    fn display_name() -> &'static str {
        "Entity behavior"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let interactive = arrays_by_descr
            .get(&Self::descriptor_interactive())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_interactive())
            });
        let visible = arrays_by_descr
            .get(&Self::descriptor_visible())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_visible()));
        let link_visibility = arrays_by_descr
            .get(&Self::descriptor_link_visibility())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_link_visibility())
            });
        Ok(Self {
            interactive,
            visible,
            link_visibility,
        })
    }
}

impl ::re_types_core::AsComponents for EntityBehavior {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [
            self.interactive.clone(),
            self.visible.clone(),
            self.link_visibility.clone(),
        ]
        .into_iter()
        .flatten()
        .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for EntityBehavior {}

impl EntityBehavior {
    /// Create a new `EntityBehavior`.
    #[inline]
    pub fn new() -> Self {
        Self {
            interactive: None,
            visible: None,
            link_visibility: None,
        }
    }

    /// Update only some specific fields of a `EntityBehavior`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `EntityBehavior`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            interactive: Some(SerializedComponentBatch::new(
                crate::components::Interactive::arrow_empty(),
                Self::descriptor_interactive(),
            )),
            visible: Some(SerializedComponentBatch::new(
                crate::components::Visible::arrow_empty(),
                Self::descriptor_visible(),
            )),
            link_visibility: Some(SerializedComponentBatch::new(
                crate::blueprint::components::LinkVisibility::arrow_empty(),
                Self::descriptor_link_visibility(),
            )),
        }
    }

    /// Whether the entity can be interacted with.
    ///
    /// This property is propagated down the entity hierarchy until another child entity
    /// sets `interactive` to a different value at which point propagation continues with that value instead.
    ///
    /// Defaults to parent's `interactive` value or true if there is no parent.
    #[inline]
    pub fn with_interactive(
        mut self,
        interactive: impl Into<crate::components::Interactive>,
    ) -> Self {
        self.interactive = try_serialize_field(Self::descriptor_interactive(), [interactive]);
        self
    }

    /// Whether the entity is visible.
    ///
    /// This property is propagated down the entity hierarchy until another child entity
    /// sets `visible` to a different value at which point propagation continues with that value instead.
    ///
    /// Defaults to parent's `visible` value or true if there is no parent.
    #[inline]
    pub fn with_visible(mut self, visible: impl Into<crate::components::Visible>) -> Self {
        self.visible = try_serialize_field(Self::descriptor_visible(), [visible]);
        self
    }

    /// Whether toggling this entity's visibility should propagate across views.
    ///
    /// When `true`, toggling this entity's `visible` override in one view also writes the same
    /// override to every other view whose contents contain this entity. Useful for keeping
    /// multi-step debug entities synchronized when you toggle them on or off.
    ///
    /// Defaults to `false` — each view manages its own visibility independently.
    #[inline]
    pub fn with_link_visibility(
        mut self,
        link_visibility: impl Into<crate::blueprint::components::LinkVisibility>,
    ) -> Self {
        self.link_visibility =
            try_serialize_field(Self::descriptor_link_visibility(), [link_visibility]);
        self
    }
}

impl ::re_byte_size::SizeBytes for EntityBehavior {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.interactive.heap_size_bytes()
            + self.visible.heap_size_bytes()
            + self.link_visibility.heap_size_bytes()
    }
}
