# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/blueprint/components/link_visibility.fbs".

# You can extend this class by creating a "LinkVisibilityExt" class in "link_visibility_ext.py".

from __future__ import annotations

from ... import datatypes
from ..._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["LinkVisibility", "LinkVisibilityBatch"]


class LinkVisibility(datatypes.Bool, ComponentMixin):
    """
    **Component**: Whether toggling an entity's visibility in one view should propagate to peer views.

    When enabled, changing the `visible` override of an entity in any view will write
    the same override into every other view whose contents include that entity. Disabled
    by default — each view manages its own visibility overrides independently.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of LinkVisibilityExt in link_visibility_ext.py

    # Note: there are no fields here because LinkVisibility delegates to datatypes.Bool


class LinkVisibilityBatch(datatypes.BoolBatch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.blueprint.components.LinkVisibility"


# This is patched in late to avoid circular dependencies.
LinkVisibility._BATCH_TYPE = LinkVisibilityBatch  # type: ignore[assignment]
